version: '3.8'

services:
  setup:
    build: setup
    init: true
    volumes:
      - distr-vol:/tmp/onlineshop-war/target

  prod:
    build:
      context: prod
      args:
        - catalina-base=/var/lib/tomcat9
        - catalina-home=/usr/share/tomcat9
    ports:
      - "8080:8080"
    volumes:
      - distr-vol:$catalina-base/webapps
    networks:
      - app-net

volumes:
  distr-vol:

networks:
  app-net:
    driver: bridge