version: '3.8'

services:
  setup:
    build: setup
    init: true
    volumes:
      - distr:/tmp/onlineshop-war/target

  prod:
    build: prod
    ports:
      - "8080:8080"
    volumes:
      - distr:/var/lib/tomcat9/webapps
    networks:
      - app-net

volumes:
  distr:

networks:
  app-net:
    driver: bridge