version: '3.8'

services:
  setup:
    build: setup
    init: true
    volumes:
      - distr-vol:/tmp/onlineshop-war/target

  prod:
    build: prod
    ports:
      - "8080:8080"
    volumes:
#       'webpapp' folder must be in catalina base folder
      - distr-vol:/var/lib/tomcat9/webapps
    networks:
      - app-net

volumes:
  distr-vol:

networks:
  app-net:
    driver: bridge